"""
Django settings for backend_colegio project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Load environment variables from a .env file (optional, for local development)
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))
except Exception:
    pass

# Optional: support parsing a DATABASE_URL (e.g. from Supabase). If you don't have
# dj-database-url installed we'll fall back to a simple SQLITE configuration.
try:
    import dj_database_url
except Exception:
    dj_database_url = None

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # El usuario debe reloguearse cada hora (seguridad)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-40-419d-kdm)p20a#bo*u&-c+pso*yp0910nus5)qky%o5su6y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',       # Para la API
    'corsheaders',          # Para permitir que React se conecte
    'gestion_academica',    # Tu app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <--- AGREGA ESTO
]

ROOT_URLCONF = 'backend_colegio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_colegio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL and dj_database_url:
    # Parse the URL and enforce SSL for hosted Postgres like Supabase
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
    # Ensure Django reuses DB connections (reduces new client connections)
    # Allow overriding via env var DATABASE_CONN_MAX_AGE (seconds)
    try:
        conn_max = int(os.getenv('DATABASE_CONN_MAX_AGE', '600'))
    except Exception:
        conn_max = 600
    # If using Supabase's connection pooler (pgbouncer in "pooler" host),
    # avoid long-lived persistent connections. Session pooling requires
    # closing DB connections after each request (CONN_MAX_AGE = 0).
    if DATABASE_URL and 'pooler.supabase.com' in DATABASE_URL:
        DATABASES['default']['CONN_MAX_AGE'] = int(os.getenv('DATABASE_CONN_MAX_AGE', '0'))
        # Health checks can create extra connections; disable to avoid pressure
        DATABASES['default']['CONN_HEALTH_CHECKS'] = False
    else:
        DATABASES['default']['CONN_MAX_AGE'] = conn_max
        # Enable health checks so Django verifies connections before using them
        # (available in recent Django versions)
        DATABASES['default']['CONN_HEALTH_CHECKS'] = True
elif DATABASE_URL and not dj_database_url:
    # If dj_database_url isn't installed, try a minimal manual parse via environment
    # Expect the user to set DATABASES via env or install dj-database-url
    raise RuntimeError('DATABASE_URL is set but `dj-database-url` is not installed. Run `pip install dj-database-url`')
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True # Solo para desarrollo, luego lo haremos más seguro

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Esto protege toda tu API por defecto
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Paginación por defecto para evitar respuestas enormes que generan muchas consultas
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}