# Generated by Django 5.2.8 on 2025-11-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=10)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.anioacademico')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.grado')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='gestion_academica.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('aula_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='gestion_academica.aula')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.padre')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.anioacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.IntegerField(default=1, help_text='Peso para promedio (ej: 1, 2, o porcentaje)')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion_academica.asignacioncurso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCursoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Editando)'), ('ENVIADO_TUTOR', 'Enviado al Tutor'), ('OBSERVADO', 'Observado (Corregir)')], default='BORRADOR', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.asignacioncurso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('es_directora', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_tutoradas', to='gestion_academica.profesor'),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_academica', to='gestion_academica.profesor'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion_academica.evaluacion')),
            ],
            options={
                'unique_together': {('evaluacion', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='Libreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PROCESO', 'En Proceso (Faltan notas)'), ('REVISION_TUTOR', 'En Revisión por Tutor'), ('ENVIADO_DIRECCION', 'Enviado a Dirección'), ('APROBADA', 'Aprobada y Visible'), ('RECHAZADA', 'Rechazada')], default='PROCESO', max_length=20)),
                ('observacion_tutor', models.TextField(blank=True, null=True)),
                ('promedio_ponderado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.alumno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.aula')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.periodo')),
            ],
            options={
                'unique_together': {('alumno', 'periodo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('grado', 'nombre_seccion', 'anio_academico')},
        ),
    ]
