# Generated by Django 5.2.8 on 2025-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreta',
            name='detalles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
