# Generated by Django 5.2.8 on 2025-11-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_add_detalles_libreta'),
        ('gestion_academica', '0002_libreta_detalles'),
    ]

    operations = [
    ]
